--Tabela de alimentos pré-cadastrada.
INSERT INTO alimentos (descricao, CF) VALUES ('ABOBORA', 68.91);
INSERT INTO alimentos (descricao, CF) VALUES ('ABOBRINHA', 37.77);
INSERT INTO alimentos (descricao, CF) VALUES ('ACAI COM GUARANA E GRANOLA', 196.53);
INSERT INTO alimentos (descricao, CF) VALUES ('AGUA, MINERAL NAO ESPECIFICADO', 20.43);
INSERT INTO alimentos (descricao, CF) VALUES ('ALCATRA', 4720.83);
INSERT INTO alimentos (descricao, CF) VALUES ('ALFACE', 63.02);
INSERT INTO alimentos (descricao, CF) VALUES ('ARROZ BRANCO', 100.81);
INSERT INTO alimentos (descricao, CF) VALUES ('ASA DE GALINHA OU FRANGO', 532.85);
INSERT INTO alimentos (descricao, CF) VALUES ('BACALHAU', 354.60);
INSERT INTO alimentos (descricao, CF) VALUES ('BANANA (OURO, PRATA, D´ÁGUA, DA TERRA, ETC)', 138.63);
INSERT INTO alimentos (descricao, CF) VALUES ('BATATA DOCE', 34.37);
INSERT INTO alimentos (descricao, CF) VALUES ('BATATA-INGLESA', 59.49);
INSERT INTO alimentos (descricao, CF) VALUES ('BETERRABA', 35.40);
INSERT INTO alimentos (descricao, CF) VALUES ('BIFE', 4243.41);
INSERT INTO alimentos (descricao, CF) VALUES ('BIFE A MILANESA', 4722.56);
INSERT INTO alimentos (descricao, CF) VALUES ('BISCOITO RECHEADO LIGHT', 164.21);
INSERT INTO alimentos (descricao, CF) VALUES ('BISTECA BOVINA', 4652.36);
INSERT INTO alimentos (descricao, CF) VALUES ('BOLO DE CENOURA', 146.27);
INSERT INTO alimentos (descricao, CF) VALUES ('BOLO DE FUBA', 204.39);
INSERT INTO alimentos (descricao, CF) VALUES ('BOLO DE LARANJA', 217.25);
INSERT INTO alimentos (descricao, CF) VALUES ('BROCOLIS', 62.61);
INSERT INTO alimentos (descricao, CF) VALUES ('CAFE COM LEITE', 69.67);
INSERT INTO alimentos (descricao, CF) VALUES ('CARNE DE PANELA', 4243.41);
INSERT INTO alimentos (descricao, CF) VALUES ('CARNE MOIDA', 4055.59);
INSERT INTO alimentos (descricao, CF) VALUES ('CARNE SECA', 5010.79);
INSERT INTO alimentos (descricao, CF) VALUES ('CARRE', 741.38);
INSERT INTO alimentos (descricao, CF) VALUES ('CEBOLA', 23.24);
INSERT INTO alimentos (descricao, CF) VALUES ('CENOURA', 46.76);
INSERT INTO alimentos (descricao, CF) VALUES ('CEREAL MATINAL DE MILHO EM FLOCOS', 290.30);
INSERT INTO alimentos (descricao, CF) VALUES ('CERVEJA (COM OU SEM ALCOOL)', 124.50);
INSERT INTO alimentos (descricao, CF) VALUES ('CERVEJA SEM ALCOOL', 124.50);
INSERT INTO alimentos (descricao, CF) VALUES ('CHAMBARIL', 4027.76);
INSERT INTO alimentos (descricao, CF) VALUES ('CHAMPANHE', 220.00);
INSERT INTO alimentos (descricao, CF) VALUES ('CHOCOLATE, TABLETE NAO ESPECIFICADO', 233.33);
INSERT INTO alimentos (descricao, CF) VALUES ('CHOPP', 124.50);
INSERT INTO alimentos (descricao, CF) VALUES ('CHUCHU', 80.77);
INSERT INTO alimentos (descricao, CF) VALUES ('COALHADA', 160.54);
INSERT INTO alimentos (descricao, CF) VALUES ('CONTRAFILE', 4720.83);
INSERT INTO alimentos (descricao, CF) VALUES ('CORACAO DE FRANGO', 447.46);
INSERT INTO alimentos (descricao, CF) VALUES ('COSTELA BOVINA', 4652.36);
INSERT INTO alimentos (descricao, CF) VALUES ('COSTELA SUINA', 741.38);
INSERT INTO alimentos (descricao, CF) VALUES ('COUVE', 70.74);
INSERT INTO alimentos (descricao, CF) VALUES ('COUVE FLOR', 55.69);
INSERT INTO alimentos (descricao, CF) VALUES ('CUPIM', 4737.86);
INSERT INTO alimentos (descricao, CF) VALUES ('DOBRADINHA FRESCA', 1148.40);
INSERT INTO alimentos (descricao, CF) VALUES ('DRUMETE DE GALINHA OU FRANGO', 532.85);
INSERT INTO alimentos (descricao, CF) VALUES ('FARINHA DE MANDIOCA', 59.40);
INSERT INTO alimentos (descricao, CF) VALUES ('FARINHA LACTEA', 290.30);
INSERT INTO alimentos (descricao, CF) VALUES ('FEIJAO (PRETO, MULATINHO, ROXO, ROSINHA, ETC)', 39.77);
INSERT INTO alimentos (descricao, CF) VALUES ('FEIJAO DE CORDA', 39.51);
INSERT INTO alimentos (descricao, CF) VALUES ('FILE DE FRANGO', 532.85);
INSERT INTO alimentos (descricao, CF) VALUES ('FILE MIGNON', 4720.83);
INSERT INTO alimentos (descricao, CF) VALUES ('FRALDINHA (CAPA DE FILE)', 4737.86);
INSERT INTO alimentos (descricao, CF) VALUES ('FRANGO A PASSARINHO', 532.85);
INSERT INTO alimentos (descricao, CF) VALUES ('IOGURTE DE QUALQUER SABOR', 343.33);
INSERT INTO alimentos (descricao, CF) VALUES ('KETCHUP', 156.00);
INSERT INTO alimentos (descricao, CF) VALUES ('LARANJA (PERA, SELETA, LIMA, DA TERRA, ETC)', 40.13);
INSERT INTO alimentos (descricao, CF) VALUES ('LAZANHA', 1032.02);
INSERT INTO alimentos (descricao, CF) VALUES ('LEITE DE VACA INTEGRAL', 126.55);
INSERT INTO alimentos (descricao, CF) VALUES ('LINGUICA (SUÍNA, BOVINA, MISTA, ETC)', 2626.20);
INSERT INTO alimentos (descricao, CF) VALUES ('LINGUICA CALABRESA', 2626.20);
INSERT INTO alimentos (descricao, CF) VALUES ('LINGUICA DE FRANGO', 651.26);
INSERT INTO alimentos (descricao, CF) VALUES ('LOMBO', 777.67);
INSERT INTO alimentos (descricao, CF) VALUES ('LOMBO SUINO', 777.67);
INSERT INTO alimentos (descricao, CF) VALUES ('MACA', 43.57);
INSERT INTO alimentos (descricao, CF) VALUES ('MACARRAO', 71.99);
INSERT INTO alimentos (descricao, CF) VALUES ('MACARRAO COM CARNE', 428.41);
INSERT INTO alimentos (descricao, CF) VALUES ('MACARRAO INSTANTANEO', 69.01);
INSERT INTO alimentos (descricao, CF) VALUES ('MAMINHA', 4720.83);
INSERT INTO alimentos (descricao, CF) VALUES ('MANDIOCA', 35.65);
INSERT INTO alimentos (descricao, CF) VALUES ('MUSCULO BOVINO', 4720.83);
INSERT INTO alimentos (descricao, CF) VALUES ('NESTON', 290.30);
INSERT INTO alimentos (descricao, CF) VALUES ('NHOQUE', 157.09);
INSERT INTO alimentos (descricao, CF) VALUES ('OVO DE GALINHA', 387.67);
INSERT INTO alimentos (descricao, CF) VALUES ('PAO DE QUEIJO', 54.71);
INSERT INTO alimentos (descricao, CF) VALUES ('PAO DE SAL', 54.71);
INSERT INTO alimentos (descricao, CF) VALUES ('PEITO DE GALINHA OU FRANGO', 494.41);
INSERT INTO alimentos (descricao, CF) VALUES ('PEIXE DE AGUA DOCE (INTEIRO, EM POSTA, EM FILÉ, ETC)', 615.47);
INSERT INTO alimentos (descricao, CF) VALUES ('PEIXE DE MAR (INTEIRO, EM POSTA, EM FILÉ, ETC)', 618.44);
INSERT INTO alimentos (descricao, CF) VALUES ('PEPINO', 56.70);
INSERT INTO alimentos (descricao, CF) VALUES ('PERNIL', 741.38);
INSERT INTO alimentos (descricao, CF) VALUES ('PICANHA', 4511.19);
INSERT INTO alimentos (descricao, CF) VALUES ('PIZZA', 558.10);
INSERT INTO alimentos (descricao, CF) VALUES ('PRESUNTO', 1152.44);
INSERT INTO alimentos (descricao, CF) VALUES ('QUEIJO MUZARELLA', 922.50);
INSERT INTO alimentos (descricao, CF) VALUES ('REFRIGERANTE DE COLA TRADICIONAL', 68.75);
INSERT INTO alimentos (descricao, CF) VALUES ('REFRIGERANTE DE GUARANA TRADICIONAL', 45.10);
INSERT INTO alimentos (descricao, CF) VALUES ('REPOLHO', 27.63);
INSERT INTO alimentos (descricao, CF) VALUES ('RUCULA', 34.94);
INSERT INTO alimentos (descricao, CF) VALUES ('SALSICHA NO VAREJO', 354.17);
INSERT INTO alimentos (descricao, CF) VALUES ('SOBRECOXA / COXA DE FRANGO / GALINHA', 532.85);
INSERT INTO alimentos (descricao, CF) VALUES ('SUCO DE LARANJA', 65.00);
INSERT INTO alimentos (descricao, CF) VALUES ('SUCO INDUSTRIALIZADO', 65.00);
INSERT INTO alimentos (descricao, CF) VALUES ('TAPIOCA', 49.22);
INSERT INTO alimentos (descricao, CF) VALUES ('TAPIOCA DE GOMA', 49.22);
INSERT INTO alimentos (descricao, CF) VALUES ('TODDYNHO', 79.44);
INSERT INTO alimentos (descricao, CF) VALUES ('TOMATE', 82.41);
INSERT INTO alimentos (descricao, CF) VALUES ('VINHO QUENTE', 126.60);
INSERT INTO alimentos (descricao, CF) VALUES ('WHISKY', 529.50);
INSERT INTO alimentos (descricao, CF) VALUES ('X-BURGUER', 996.40);
